services:
  - type: web
    name: fateen-renderer
    runtime: docker
    plan: free
    dockerfilePath: ./render-service/Dockerfile
    dockerContext: ./render-service
    healthCheckPath: /
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
